### ISSUE TITLE
Current Batch does not clear and populate with new generations

### ISSUE THREAD

**Issue by Gushousekai195** [dvruette/sd-webui-fabric#4]
Whenever I generate new images the previous generations are not cleared from the Current batch window and I am unable to make feedback on the new images.

The only workaround is to drag the new images into the Upload Image window and make feedback there

**Comment by dvruette** [comment]
Yes I believe I'm aware of this issue. A workaround currently is to just close and re-open the selected image or to change the selection to a different image. It's a limitation where I'm only able to detect when a new image is selected but not when the image changes due to new generation results. Still looking for a way to solve this.

**Comment by cashea** [comment]
I am having this same problem.

**Comment by Xyem** [comment]
Also experiencing this but cannot use the workaround as I am using a batch size of 1, so I can't move off the selected image at all.
